Attachments:
  type: entity
  table: attachments
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    issueId:
      type: integer
      unsigned: false
      nullable: false
      column: issue_id
    name:
      type: string
      length: 64
      fixed: false
      nullable: false
    description:
      type: text
      nullable: false
    url:
      type: string
      length: 255
      fixed: false
      nullable: false
    submittedBy:
      type: integer
      unsigned: false
      nullable: true
      column: submitted_by
    submittedOn:
      type: datetime
      nullable: true
      column: submitted_on
  lifecycleCallbacks: {  }
