Comments:
  type: entity
  table: comments
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    issueId:
      type: integer
      unsigned: false
      nullable: false
      column: issue_id
    commentId:
      type: integer
      unsigned: false
      nullable: true
      column: comment_id
    text:
      type: text
      nullable: false
    submittedBy:
      type: integer
      unsigned: false
      nullable: false
      column: submitted_by
    submittedOn:
      type: datetime
      nullable: false
      column: submitted_on
  lifecycleCallbacks: {  }
