People:
  type: entity
  table: people
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 64
      fixed: false
      nullable: true
    email:
      type: string
      length: 64
      fixed: false
      nullable: true
    userId:
      type: string
      length: 64
      fixed: false
      nullable: false
      column: user_id
    trackerId:
      type: integer
      unsigned: false
      nullable: false
      column: tracker_id
  lifecycleCallbacks: {  }
