Iccs\CvsanalyDbBundle\Entity\Metrics:
  type: entity
  table: metrics
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    fileId:
      type: integer
      unsigned: false
      nullable: true
      column: file_id
    commitId:
      type: integer
      unsigned: false
      nullable: true
      column: commit_id
    lang:
      type: text
      nullable: true
    sloc:
      type: integer
      unsigned: false
      nullable: true
    loc:
      type: integer
      unsigned: false
      nullable: true
    ncomment:
      type: integer
      unsigned: false
      nullable: true
    lcomment:
      type: integer
      unsigned: false
      nullable: true
    lblank:
      type: integer
      unsigned: false
      nullable: true
    nfunctions:
      type: integer
      unsigned: false
      nullable: true
    mccabeMax:
      type: integer
      unsigned: false
      nullable: true
      column: mccabe_max
    mccabeMin:
      type: integer
      unsigned: false
      nullable: true
      column: mccabe_min
    mccabeSum:
      type: integer
      unsigned: false
      nullable: true
      column: mccabe_sum
    mccabeMean:
      type: integer
      unsigned: false
      nullable: true
      column: mccabe_mean
    mccabeMedian:
      type: integer
      unsigned: false
      nullable: true
      column: mccabe_median
    halsteadLength:
      type: integer
      unsigned: false
      nullable: true
      column: halstead_length
    halsteadVol:
      type: integer
      unsigned: false
      nullable: true
      column: halstead_vol
    halsteadLevel:
      type: float
      nullable: true
      column: halstead_level
    halsteadMd:
      type: integer
      unsigned: false
      nullable: true
      column: halstead_md
  lifecycleCallbacks: {  }
