Iccs\StardomBundle\Entity\FileLinks:
  type: entity
  table: file_links
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    parentId:
      type: integer
      unsigned: false
      nullable: true
      column: parent_id
    fileId:
      type: integer
      unsigned: false
      nullable: true
      column: file_id
    commitId:
      type: integer
      unsigned: false
      nullable: true
      column: commit_id
  lifecycleCallbacks: {  }
